set(_CATKIN_CURRENT_PACKAGE "python_script")
set(python_script_VERSION "0.0.0")
set(python_script_MAINTAINER "osboxes <osboxes@todo.todo>")
set(python_script_PACKAGE_FORMAT "2")
set(python_script_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(python_script_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(python_script_BUILDTOOL_DEPENDS "catkin")
set(python_script_BUILDTOOL_EXPORT_DEPENDS )
set(python_script_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(python_script_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(python_script_TEST_DEPENDS )
set(python_script_DOC_DEPENDS )
set(python_script_DEPRECATED "")